RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - DEBUG - Explicitly setting the multiprocessing start method to 'spawn'
RealTimeSTT: root - DEBUG - Start method has already been set. Details: context has already been set
RealTimeSTT: root - INFO - Starting RealTimeSTT
RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
RealTimeSTT: root - INFO - Initializing faster_whisper realtime transcription model base
RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-base/revision/main HTTP/11" 200 1848
RealTimeSTT: root - DEBUG - Faster_whisper realtime speech to text transcription model initialized successfully
RealTimeSTT: root - DEBUG - Porcupine wake word detection engine initialized successfully
RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Softwares\Anaconda\envs\dev\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Softwares\Anaconda\envs\dev\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Softwares\Anaconda\envs\dev\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
RealTimeSTT: root - DEBUG - Starting recording worker
RealTimeSTT: root - DEBUG - Starting realtime worker
RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
RealTimeSTT: root - DEBUG - Main transcription model ready
RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
RealTimeSTT: root - DEBUG - Explicitly setting the multiprocessing start method to 'spawn'
RealTimeSTT: root - DEBUG - Start method has already been set. Details: context has already been set
RealTimeSTT: root - INFO - Starting RealTimeSTT
RealTimeSTT: root - INFO - Initializing audio recording (creating pyAudio input stream, sample rate: 16000 buffer size: 512
RealTimeSTT: root - INFO - Initializing faster_whisper realtime transcription model base
RealTimeSTT: urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): huggingface.co:443
RealTimeSTT: urllib3.connectionpool - DEBUG - https://huggingface.co:443 "GET /api/models/Systran/faster-whisper-base/revision/main HTTP/11" 200 1848
RealTimeSTT: root - DEBUG - Faster_whisper realtime speech to text transcription model initialized successfully
RealTimeSTT: root - DEBUG - Porcupine wake word detection engine initialized successfully
RealTimeSTT: root - INFO - Initializing WebRTC voice with Sensitivity 3
RealTimeSTT: root - DEBUG - WebRTC VAD voice activity detection engine initialized successfully
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg6
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Softwares\Anaconda\envs\dev\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg5
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Softwares\Anaconda\envs\dev\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg4
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "D:\Softwares\Anaconda\envs\dev\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Softwares\Anaconda\envs\dev\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
RealTimeSTT: torio._extension.utils - DEBUG - Loading FFmpeg
RealTimeSTT: torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
RealTimeSTT: root - DEBUG - Silero VAD voice activity detection engine initialized successfully
RealTimeSTT: root - DEBUG - Starting recording worker
RealTimeSTT: root - DEBUG - Starting realtime worker
RealTimeSTT: root - DEBUG - Waiting for main transcription model to start
RealTimeSTT: root - DEBUG - Main transcription model ready
RealTimeSTT: root - DEBUG - RealtimeSTT initialization completed successfully
RealTimeSTT: root - ERROR - Error initializing openwakeword wake word detection engine: Could not find pretrained model for model name 'suh_man_tuh.onnx'
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\RealtimeSTT\audio_recorder.py", line 570, in __init__
    self.owwModel = Model(
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\openwakeword\utils.py", line 686, in wrapped
    return func(*args, **new_kwargs)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\openwakeword\model.py", line 97, in __init__
    raise ValueError("Could not find pretrained model for model name '{}'".format(i))
ValueError: Could not find pretrained model for model name 'suh_man_tuh.onnx'
RealTimeSTT: root - ERROR - Error initializing openwakeword wake word detection engine: Could not find pretrained model for model name 'suh_man_tuh.onnx'
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\RealtimeSTT\audio_recorder.py", line 570, in __init__
    self.owwModel = Model(
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\openwakeword\utils.py", line 686, in wrapped
    return func(*args, **new_kwargs)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\openwakeword\model.py", line 97, in __init__
    raise ValueError("Could not find pretrained model for model name '{}'".format(i))
ValueError: Could not find pretrained model for model name 'suh_man_tuh.onnx'
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 11. Discarding old audio chunks.
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 11. Discarding old audio chunks.
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 12. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 12. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 25. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Error initializing Silero VAD voice activity detection engine: Remote end closed connection without response
Traceback (most recent call last):
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\RealtimeSTT\audio_recorder.py", line 629, in __init__
    self.silero_vad_model, _ = torch.hub.load(
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\hub.py", line 565, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, trust_repo, "load",
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\hub.py", line 206, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "D:\Softwares\Anaconda\envs\dev\lib\site-packages\torch\hub.py", line 150, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "D:\Softwares\Anaconda\envs\dev\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Softwares\Anaconda\envs\dev\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\Softwares\Anaconda\envs\dev\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Softwares\Anaconda\envs\dev\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\Softwares\Anaconda\envs\dev\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Softwares\Anaconda\envs\dev\lib\urllib\request.py", line 1350, in do_open
    r = h.getresponse()
  File "D:\Softwares\Anaconda\envs\dev\lib\http\client.py", line 1377, in getresponse
    response.begin()
  File "D:\Softwares\Anaconda\envs\dev\lib\http\client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "D:\Softwares\Anaconda\envs\dev\lib\http\client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 173. Discarding old audio chunks.
RealTimeSTT: faster_whisper - WARNING - An error occured while synchronizing the model Systran/faster-whisper-base from the Hugging Face Hub:
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/Systran/faster-whisper-base/revision/main (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1133)')))"), '(Request ID: 6fa34a0d-012c-44d8-a791-1af025d703b6)')
RealTimeSTT: faster_whisper - WARNING - Trying to load the model directly from the local cache, if it exists.
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 1073. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 38. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 12. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 12. Discarding old audio chunks.
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: max() arg is an empty sequence
RealTimeSTT: root - WARNING - Audio queue size exceeds latency limit. Current size: 12. Discarding old audio chunks.
